In [5]:
import pandas as pd
import numpy as np

#np array's are precompiled. Hence, they are faster than lists
distance =[45,50,55]
time = [9,10,11]

adistance = np.array(distance)
atime =np.array(time)
speed = adistance/atime

speed

array([5., 5., 5.])

In [13]:
a = [5,6,7,8,9]
b=[1,2,3,4,5]
#add 5 to each of the list elements in a
a = np.array(a)
c = a+5
c
# add elements in a to b
b = np.array(b)
d=a+b
d

array([ 6,  8, 10, 12, 14])

In [18]:
#find the data type of the array, a
a.dtype

dtype('int64')

In [26]:
#explore the function arange. It generates a range of numbers for a sequence which can act as a counter
e=np.arange(10)
print( e)
e=np.arange(-3)
print( e)
e=np.arange(5.0)
print( e)
e=np.arange(5,56,5) # seed is 5, limit is 56, increment is 5
print( e)

[0 1 2 3 4 5 6 7 8 9]
[]
[0. 1. 2. 3. 4.]
[ 5 10 15 20 25 30 35 40 45 50 55]


In [30]:
#explore the function linspace. Python for creating numeric sequences. It's somewhat similar to the NumPy arange 
#function, in that it creates sequences of evenly spaced numbers structured as a NumPy array

print(np.linspace(20,30,10))
np.linspace(20,30,num=10,endpoint=False) #skips the last number in the sequence

[20.         21.11111111 22.22222222 23.33333333 24.44444444 25.55555556
 26.66666667 27.77777778 28.88888889 30.        ]


array([20., 21., 22., 23., 24., 25., 26., 27., 28., 29.])

In [44]:
data = np.array((1,2,3,4,5,6,7,8,9,99,88,77,66,55,44,33,22,11,111,112,113,114,115,116))
print(data)
#convert one dimensrional array to two using the reshape function. reshape can be used to 
#convert to multiple dimensions
data = data.reshape(8,3)
print(data)
data1 = data.reshape(2,2,6)
print(data1)
data2 = data.reshape(2,2,3,2)
print(data2)

[  1   2   3   4   5   6   7   8   9  99  88  77  66  55  44  33  22  11
 111 112 113 114 115 116]
[[  1   2   3]
 [  4   5   6]
 [  7   8   9]
 [ 99  88  77]
 [ 66  55  44]
 [ 33  22  11]
 [111 112 113]
 [114 115 116]]
[[[  1   2   3   4   5   6]
  [  7   8   9  99  88  77]]

 [[ 66  55  44  33  22  11]
  [111 112 113 114 115 116]]]
[[[[  1   2]
   [  3   4]
   [  5   6]]

  [[  7   8]
   [  9  99]
   [ 88  77]]]


 [[[ 66  55]
   [ 44  33]
   [ 22  11]]

  [[111 112]
   [113 114]
   [115 116]]]]


In [47]:
#print the even numbers from the data array
even_numbers = (data % 2 == 0)
print(data[even_numbers])
#print 10 zeros consecutively using zeros
np.zeros(10)

[  2   4   6   8  88  66  44  22 112 114 116]


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [48]:
#create an identity matrix for 5 matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

The history saving thread hit an unexpected error (OperationalError('database or disk is full')).History will not be written to the database.
